steps:

# CONTAINERIZE: containerize the application
- name: gcr.io/cloud-builders/docker
  entrypoint: docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']

# PUSH: push container image to registry
- name: gcr.io/cloud-builders/docker
  entrypoint: docker
  args: ['push','gcr.io/$PROJECT_ID/hello']

# DEPLOY: deploy application to Cloud Run 
- name: gcr.io/cloud-builders/gcloud
  entrypoint: gcloud
  args: 
    [
      "beta","run","deploy","${_CLOUD_RUN_SERVICE_NAME}",
      "--image=gcr.io/$PROJECT_ID/hello",
      "--platform=managed",
      "--region=us-central1",
      "--allow-unauthenticated"
    ]
substitutions:
  _CLOUD_RUN_SERVICE_NAME: hello