steps:

  # CONTAINERIZE: containerize the application
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']

  # PUSH: push container image to registry
  - name: gcr.io/cloud-builders/docker
    entrypoint: docker
    args: ['push','gcr.io/$PROJECT_ID/hello']

  # DEPLOY: deploy application to Cloud Run 
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gcloud
    args: 
      [
          "beta","run","deploy","${_CLOUD_RUN_SERVICE_NAME}",
          "--image=gcr.io/$PROJECT_ID/hello",
          "--platform=managed",
          "--region=us-central1",
          "--allow-unauthenticated"
      ]

  # add preview URL as a comment on Pull Request
  - name: gcr.io/cloud-builders/curl
    entrypoint: bash
    args: 
      - "-c"
      - |
        echo hi
    secretEnv: 
      - GITHUB_TOKEN

substitutions:
    _CLOUD_RUN_SERVICE_NAME: hello
    _CLOUD_RUN_STAGING_URL: staging.cloudbuild.demo.stanke.dev

secrets:
  - kmsKeyName: projects/gcb-demo/locations/global/keyRings/gcb-demo/cryptoKeys/cloudbuild-demo-github
    secretEnv:
        GITHUB_TOKEN: "\
        CiQAd0xfMxvWgCnWVxUwmsMwBrUgee59+mipaSp42kiL8UUY9P4SUgAQ7EEUEMH\
        bzYr8/8cwmRw4sJYxSTRk2Jqr2HHVjLbb7tt6KXDAWtttL4R+G2/jglJv/KRsL4t\
        8JRmPC9mvI/BQ31nI6JJIEDZpTsg3AKAv3/w="